name: geoist
channels:
        - conda-forge
        - defaults
dependencies:
        - python>=3.5
        - numpy
        - h5py
        - impactutils
        - ipython
        - libcomcat
        - matplotlib
        - pandas
        - pytest
        - pytest-cov
        - rasterio
        - scipy
        - shapely
        - obspy
        - cartopy
        - gdal
        - argparse
        - pip:
                - pygmi
                - MarkDown
                - rasterio
